# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

Metrics/CyclomaticComplexity:
  Max: 10

AllCops:
  Exclude:
    - "src/modules/*.rb"
    - "src/clients/firewall_auto.rb"
    - "src/include/*/*.rb"
